const bridge = window.AstrBotPluginPage;
const $ = (s) => document.querySelector(s);
let state, tab = "workflows", draft, busy = false;
const names = { queued:"待提交", submitting:"提交中", submission_unknown:"提交未确认", running:"生成中", tracking_paused:"跟踪暂停", completed:"生成完成", failed:"失败", pending:"尚未发送", sending:"发送中", sent:"调用成功", unknown:"结果未确认" };
const node = (tag, text, cls) => { const e=document.createElement(tag); if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e; };
const append = (e,...children) => { e.append(...children.filter(Boolean));return e; };
const btn = (text, fn, cls="") => { const b=node("button",text,cls);b.type="button";b.onclick=fn;return b; };
const tag = (status) => node("span",names[status]||status,`tag ${status}`);
function notice(text,error=false){$("#notice").textContent=text;$("#notice").className=error?"error":"";}
async function work(fn){if(busy)return;busy=true;try{await fn();}catch(e){notice(e.message,true);}finally{busy=false;}}
async function read(){state=await bridge.apiGet("state");$("#footer").textContent=`版本 ${state.version} · 自动跟进任务 · 图片不会自动预览`;}
async function action(data){const result=await bridge.apiPost("action",data);await read();render();notice("已完成");return result;}
function field(title,name,value,type="text"){const label=node("label",undefined,"field");const input=node(type==="textarea"?"textarea":"input");if(type!=="textarea")input.type=type;input.name=name;input.value=value??"";return append(label,node("span",title),input);}
function toolbar(title,subtitle,button){return append(node("div",undefined,"toolbar"),append(node("div"),node("h2",title),node("p",subtitle,"muted")),button);}
function workflows(){const root=node("div");root.append(toolbar("让工作流各司其职",`${state.workflows.length} 个工作流 · 模型和采样参数保留在工作流中`,btn("＋ 上传工作流",()=>$("#upload").click())));const cards=node("div",undefined,"cards");for(const w of state.workflows){const card=node("article",undefined,"card");card.append(append(node("div",undefined,"card-head"),node("h3",w.name),tag(w.enabled?"已启用":"disabled")),node("p",w.short||"尚未填写简单介绍"),append(node("div",undefined,"facts"),tag(`${w.bindings.texts.length} 个文字入口`),tag(`${w.bindings.images.length} 张参考图`),tag(w.bindings.width.length?"可选尺寸":"默认尺寸")),append(node("div",undefined,"actions"),btn("编辑",()=>edit(structuredClone(w))),btn(w.enabled?"停用":"启用",()=>work(()=>action({action:"save_workflow",workflow:{...w,enabled:!w.enabled}})),"secondary"),btn("删除",()=>{if(confirm(`删除工作流「${w.name}」？已有任务记录仍保留。`))work(()=>action({action:"delete_workflow",id:w.id}));},"danger")));cards.append(card);}root.append(cards);if(!state.workflows.length)root.append(node("p","上传 ComfyUI API JSON，即可配置文字、图片和尺寸入口。","empty"));return root;}
function tasks(){const root=node("div");root.append(toolbar("每张图，都有明确的去向","生成完成和发送成功分别记录；重发只使用原图。",btn("刷新状态",()=>work(async()=>{for(const t of state.tasks.filter(t=>["running","submission_unknown","tracking_paused"].includes(t.generation)))await bridge.apiPost("action",{action:"refresh_task",id:t.id});await read();render();}),"secondary")));const panel=node("div",undefined,"panel");for(const t of state.tasks){const row=node("article",undefined,"task");row.append(append(node("div"),node("h3",t.workflow_name),node("p",new Date(t.created*1000).toLocaleString(),"muted"),node("p",t.width?`${t.width} × ${t.height}`:"工作流默认尺寸","muted")),append(node("div"),node("p","生成状态","muted"),tag(t.generation)),append(node("div"),node("p",t.files_expired?"图片已过期":"发送状态","muted"),tag(t.delivery)));const actions=node("div",undefined,"actions");actions.append(btn("查询",()=>work(()=>action({action:"refresh_task",id:t.id})),"secondary"));const resend=btn("重发原图",()=>{const extra=t.delivery==="unknown"?"此前发送结果未确认，重发可能重复。":"";if(confirm(`${extra}将原图重发到原会话，继续？`))work(()=>action({action:"resend",id:t.id}));});resend.disabled=t.generation!=="completed"||t.files_expired;actions.append(resend);row.append(actions);const details=node("details");details.append(node("summary",t.error?`查看原因：${t.error}`:"查看会话与发送尝试"),node("pre",JSON.stringify({task:t.id,scope:t.scope,owner:t.owner,error:t.error,attempts:t.attempts},null,2)));row.append(details);panel.append(row);}if(!state.tasks.length)panel.append(node("p","还没有绘图任务。向机器人描述你想画的内容即可。","empty"));root.append(panel);return root;}
function settings(){const root=node("div");root.append(toolbar("连接与默认规则","每次绘图发送开始提示与最终结果。AI 的中间进度话由插件处理。"));const form=node("form",undefined,"panel settings");const labels={server_url:"ComfyUI 服务地址",min_edge:"最小边长",max_edge:"最大边长",multiple:"尺寸倍数",max_pixels:"最大总像素",record_days:"任务记录保留（天）",image_days:"图片保留（天）",poll_seconds:"后台查询间隔（秒）",tracking_minutes:"单次跟踪时长（分钟）"};for(const [k,title] of Object.entries(labels)){const f=field(title,k,state.settings[k],k==="server_url"?"text":"number");if(k==="server_url")f.classList.add("wide");form.append(f);}const submit=node("button","保存设置");submit.type="submit";form.append(append(node("div",undefined,"actions wide"),submit,btn("按保留规则清理",()=>work(()=>action({action:"cleanup"})),"secondary")));form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));for(const k of Object.keys(data))if(k!=="server_url")data[k]=Number(data[k]);work(()=>action({action:"settings",settings:data}));};root.append(form);return root;}
function render(){if(!state)return;$("#content").replaceChildren(({workflows,tasks,settings})[tab]());document.querySelectorAll("nav button").forEach(b=>{if(b.dataset.tab===tab)b.setAttribute("aria-current","page");else b.removeAttribute("aria-current");});}
function infer(graph){const b={texts:[],images:[],width:[],height:[],outputs:[]};for(const [id,n] of Object.entries(graph)){if(!n||!n.inputs)continue;const input=n.inputs;if(n.class_type==="Simple String"){const k=["text","string"].find(k=>k in input);if(k)b.texts.push({node:id,input:k,label:"绘画描述 / 修改要求"});}if(n.class_type==="ETN_LoadImageBase64")b.images.push({node:id,input:"image",label:`图片${b.images.length+1}`});if(["EmptyLatentImage","EmptySD3LatentImage"].includes(n.class_type))for(const k of ["width","height"])if(k in input)b[k].push({node:id,input:k});if(n.class_type==="SaveImage")b.outputs.push(id);}return b;}
function syncFields(){if(!draft)return;const form=$("#workflow-form");for(const k of ["name","short","detailed"])draft[k]=form.elements[k]?.value??draft[k];}
function select(items,value){const el=node("select");for(const [v,label] of items){const o=node("option",label);o.value=v;el.append(o);}el.value=value;return el;}
function bindings(kind,title){const section=node("section",undefined,"binding-section");const rows=draft.bindings[kind];section.append(append(node("div",undefined,"binding-head"),node("h3",title),btn("＋ 入口",()=>{syncFields();const id=Object.keys(draft.graph)[0];rows.push({node:id,input:Object.keys(draft.graph[id].inputs)[0],label:title});edit(draft);},"secondary")));rows.forEach((r,index)=>{const row=node("div",undefined,"binding");const nodes=select(Object.entries(draft.graph).map(([id,n])=>[id,`${id} · ${n._meta?.title||n.class_type}`]),r.node);nodes.setAttribute("aria-label",`${title}${index+1}节点`);const inputs=select(Object.keys(draft.graph[r.node]?.inputs||{}).map(k=>[k,k]),r.input);inputs.setAttribute("aria-label",`${title}${index+1}输入字段`);nodes.onchange=()=>{syncFields();r.node=nodes.value;r.input=Object.keys(draft.graph[r.node].inputs)[0];edit(draft);};inputs.onchange=()=>r.input=inputs.value;const label=node("input");label.value=r.label||"";label.placeholder="槽位说明";label.setAttribute("aria-label",`${title}${index+1}说明`);label.oninput=()=>r.label=label.value;row.append(nodes,inputs,label,btn("×",()=>{syncFields();rows.splice(index,1);edit(draft);},"danger"));section.append(row);});return section;}
function edit(w){draft=w;const root=$("#editor-content");root.replaceChildren(field("工作流名称","name",w.name),field("简单介绍","short",w.short),field("详细介绍","detailed",w.detailed,"textarea"));root.append(node("div","入口按从上到下的顺序接收 AI 输入。宽高会覆盖本次任务的指定输入，不修改模板。","request-note"));for(const [kind,title] of [["texts","文字入口"],["images","图片入口"],["width","宽度入口"],["height","高度入口"]])root.append(bindings(kind,title));const output=node("section",undefined,"binding-section");output.append(node("h3","最终图片输出节点"));for(const [id,n] of Object.entries(w.graph)){const label=node("label",undefined,"output");const check=node("input");check.type="checkbox";check.checked=w.bindings.outputs.includes(id);check.onchange=()=>{w.bindings.outputs=check.checked?[...w.bindings.outputs,id]:w.bindings.outputs.filter(x=>x!==id);};label.append(check,document.createTextNode(`${id} · ${n._meta?.title||n.class_type}`));output.append(label);}root.append(output);if(!$("#editor").open)$("#editor").showModal();}
$("#workflow-form").onsubmit=e=>{e.preventDefault();syncFields();work(async()=>{await action({action:"save_workflow",workflow:draft});$("#editor").close();});};
$("#close").onclick=()=>$("#editor").close();
$("#upload").onchange=()=>work(async()=>{const file=$("#upload").files[0];if(!file)return;if(file.size>20*1024*1024)throw Error("文件超过 20 MB");const graph=JSON.parse(await file.text());if(!graph||Array.isArray(graph)||graph.nodes||!Object.keys(graph).length)throw Error("请上传 API 格式 JSON");edit({name:file.name.replace(/\.json$/i,"").split("+")[0],short:"",detailed:"",enabled:true,graph,bindings:infer(graph)});$("#upload").value="";});
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});$("#refresh").onclick=()=>work(async()=>{await read();render();notice("已刷新");});
try{if(!bridge)throw Error("请从 AstrBot 插件的 Pages 入口打开管理页");await bridge.ready();await read();render();setInterval(()=>{if(tab==="tasks"&&!busy&&!document.hidden&&!$("#editor").open)work(async()=>{await read();render();});},5000);}catch(e){notice(e.message,true);$("#content").replaceChildren(node("p","暂时无法连接，请确认插件已启用。","empty"));}
